#!/bin/sh

link=$(termux-clipboard-get)
case $link in
    *youtu*)
	    echo "please wait.. generating link & opening link"
	    mpv "$(yt-dlp -f b --get-url "$link")";;
    *)
	    echo "no youtube link found";;
esac
exit 0
