#!/bin/sh

[ -z "$*" ] && printf "enter number:" && read -r num || num=$*

mkdir -p $HOME/.cache/$num
dir="$HOME/.cache/$num"
trap "rm -rf $dir;exit 0" INT HUP
pg=$(curl -s "https://nhentai.net/g/$num/1/" | sed -nE 's/.*pages">(.*)<\/span><.*/\1/p')
echo "pages : $pg"
for i in $(seq $pg);do
	url=$(curl -s "https://nhentai.net/g/$num/$i/" | sed -nE 's/.*<img src="([^"]*)".*/\1/p')
	i_t=$(printf "%03d" $i)
	echo "downloading page $i/$pg"
	setsid -f curl -s "$url" -o "$dir/$i_t"
	sleep 1
done

echo "waiting 5 sec for pages to download completely"
sleep 5
echo "concat pages to pdf"
convert "$dir/*" "7689-5BBD/$num.pdf" && echo "saved pdf in 7689-5BBD/$num.pdf\nenjoy 😏😏"
rm -rf $dir
