#!/bin/sh

c_red="\033[1;31m"
c_green="\033[1;32m"
c_yellow="\033[1;33m"
c_blue="\033[1;34m"
c_magenta="\033[1;35m"
c_cyan="\033[1;36m"
c_reset="\033[0m"

while :; do
    printf "\n${c_yellow}Wifi Remote>>\n${c_blue}[c]cast <data>\n${c_magenta}[u]vol up 5\n${c_magenta}[d]vol down 5\n${c_green}[v]volume <data>\n${c_cyan}[p]Play/Pause\n${c_blue}[i]video Info\n${c_red}[q]Quit"
printf "\n${c_reset}Enter choice:${c_green}"
    read choice data
    tput clear
    case $choice in
        c)      catt cast "$data";;
        u)      catt volumeup 5;;
        d)      catt volumedown 5;;
        v)      catt volume $data;;
        p)      catt play_toggle;;
        i)      catt status;;
        q)      break;;
    esac 
done
