#!/bin/sh

echo "please wait.. downloading rss..\n"
curl -s https://subsplease.org/rss/?r=720 | tr "><" ">\n<"  > .cache/rss

name=$(sed -n -e 's/title>\(\[SubsPlease\].*\)/\1/p' .cache/rss | sed -e 's/\[SubsPlease\] //g' -e 's/(.*//g' | fzf)

echo "$name\n" 

query=$(echo $name | sed 's/ /\%20/g')
magnet=$(sed -n -e "s/link>\(.*$query.*\).*/\1/p" .cache/rss)

echo $magnet

./torrent "$magnet"
