#!/bin/sh

[ -e ".tts" ] || mkfifo ~/.tts
while true; do cat ~/.tts; done | termux-tts-speak -p 1.5 -s MUSIC -r 2.0 &
trap "printf '\033[2K\r\033[1;31mBye\n';rm -f ~/.tts;killall -q sh termux-api cat;exit 0" INT HUP

while true; do
    printf "\033[1;34mSpeak > \033[0m"
    read x
    case $x in
	!q)
	    printf '\033[2K\r\033[1;31mBye\n'
	    rm -f ~/.tts
	    killall -q sh termux-api cat
	    exit 0;;
	!*)
	    printf "\033[A\033[2K\r< \033[1;35m$x > \033[1;32m"
	    printf "$x\n" | tr -d "!" | sh | tee ~/.tts;;
	*)
	    printf "\033[A\033[2K\r< \033[1;32m"
	    printf "$x\n" | tee ~/.tts;;
    esac
done
