#!/bin/sh

if [ -z "$*" ]; then
	magnet=$(termux-clipboard-get)
else
	magnet=$*
fi

termux-notification --ongoing -i 2 -t "Torrent" -c "Rukk ja download ho rha hai"
echo "$magnet"
(aria2c --dir=/storage/7689-5BBD --seed-time=0 "$magnet" && termux-notification -t "Torrent" -c "cheecha download hogyi" || termux-notification -t "Torrent" -c "cheecha error!!") 
termux-notification-remove 2
