#!/bin/sh

c_red="\033[1;31m"
c_green="\033[1;32m"
c_yellow="\033[1;33m"
c_blue="\033[1;34m"
c_magenta="\033[1;35m"
c_cyan="\033[1;36m"
c_reset="\033[0m"

full_tor(){
    tput reset
    termux-notification -i 2 -t "Torrent" -c "Rukk ja download ho rha hai"
    (aria2c --summary-interval=0 --dir=/storage/7689-5BBD --seed-time=0 "$1" && termux-notification -i 2 -t "Torrent" -c "cheecha download hogyi" || termux-notification -i 2 -t "Torrent" -c "cheecha error!!") 
}

part_tor(){
    aria2c --dir=$HOME/.cache --bt-metadata-only=true --bt-save-metadata=true "$1"
    tput reset
    aria2c --show-files=true $HOME/.cache/*.torrent 
    printf "\nEnter idx(default all):"
    read -r ind
    termux-notification -i 2 -t "Torrent" -c "Rukk ja download ho rha hai"
    (aria2c --summary-interval=0 --select-file=$ind --dir=/storage/7689-5BBD --seed-time=0 $HOME/.cache/*.torrent && termux-notification -i 2 -t "Torrent" -c "cheecha download hogyi" || termux-notification -i 2 -t "Torrent" -c "cheecha error!!") 
    rm -f $HOME/.cache/*.torrent
}

trap "rm -f $HOME/.cache/*.torrent;exit 0" INT HUP

if [ -z "$*" ]; then
	magnet=$(termux-clipboard-get)
else
	magnet=$*
fi

echo "$magnet"
printf "${c_yellow}Download>>\n${c_green}[f]ull torrent\n${c_cyan}[p]artial torrent \n${c_red}[q]uit"
printf "${c_reset}\n\tenter choice:"
read -r ch
case $ch in
    f)
	full_tor "$magnet";;
    p)
	part_tor "$magnet";;
    q)
	exit 0;;
esac
