#!/bin/sh

# script for downloading youtube videos and split it into pieces..

# defining shell colors for distinction
c_red="\033[1;31m"
c_green="\033[1;32m"
c_yellow="\033[1;33m"
c_blue="\033[1;34m"
c_magenta="\033[1;35m"
c_cyan="\033[1;36m"
c_reset="\033[0m"

#function to download full video
full()
{
	[ -z "$2" ] &&
	yt-dlp "$1" -o "/storage/7689-5BBD/%(title)s.%(ext)s" ||
	yt-dlp -f 'ba' -x --audio-format mp3 "$1" -o "/storage/7689-5BBD/%(title)s.%(ext)s"
}

part()
{
	printf "${c_magenta}Enter Starting Point(hh:mm:ss)or(mm:ss)${c_reset}:"
	read start
	printf "${c_yellow}Enter Upto Seconds:${c_cyan}"
	read dur
	[ -z "$2" ] &&
	ffmpeg -i $(yt-dlp -f b --get-url "$1") -ss $start -t $dur -map 0 -codec copy /storage/7689-5BBD/$(date +%s).mp4 ||
	ffmpeg -i $(yt-dlp -f 'ba' --get-url "$1") -ss $start -t $dur -map a -q:a 0 /storage/7689-5BBD/$(date +%s).mp3
}

#program starts from here..
x=$(termux-clipboard-get)
printf "\n${c_blue} video link :${c_magenta}$x\n"
printf "${c_yellow}Download>>\n${c_blue}[a]Audio only\n${c_magenta}[f]part of Audio only\n${c_green}[v]Full video\n${c_cyan}[p]Part of video\n${c_red}[q]Quit"
printf "\n${c_reset}Enter choice:${c_green}"
read choice
case $choice in
	a)
		full "$x" "1" && termux-notification -c "audio downloaded";;
	f)
		part "$x" "1" && termux-notification -c "audio downloaded";;
	v)
		full "$x" && termux-notification -c "video downloaded";;
	p)
		part "$x" && termux-notification -c "video downloaded";;
	q)
		break;;
esac
